version: "3"

networks:
    myNetwork:
        driver: bridge

services:

    planner:
        build:
            context: ./planner/
            dockerfile: ./DockerFile
        networks:
            - "myNetwork"
        ports:
            - "3000:3000"
        environment:
            TASKS: '4'
            ADD: 'http://add:3001'
            MULT: 'http://mult:3002'
        depends_on: 
            - "add"
            - "mult"

    add:
        build:
            context: ./worker
            dockerfile: ./DockerFile
        ports: 
            - "3001:3001"
        networks:
            - "myNetwork"
        environment:
            ADD: 'true'
            PORT: '3001'


    mult:
        build:
            context: ./worker
            dockerfile: ./DockerFile
        ports:
            - "3002:3002"
        networks:
            - "myNetwork"
        environment:
            MULT: 'true'
            PORT: '3002'